name: add_datasets

on:
  workflow_dispatch:
  push:
    paths:
      - 'data/*_finanziate.csv'

concurrency: 
  group: ${{ github.ref }}

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4
        - name: Set up Python 3.x
          uses: actions/setup-python@v5
          with:
            python-version: "3.10"
            architecture: "x64"
        - name: Install deps
          working-directory: .
          run: pip install -r assets/requirements.txt
        - name: Execute script Split
          working-directory: .
          run: python assets/script/split_avvisi.py
        - name: Execute script KPI
          working-directory: .
          run: python assets/script/build_kpis.py
        - name: Commit
          uses: EndBug/add-and-commit@v9
          with:
            message: 'Aggiunti dataset con split per avviso'
            add: 'data'

